name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install dev tools (ruff, mypy)
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy
      - name: Lint with ruff
        run: ruff check .
      - name: Type-check with mypy (lenient)
        run: mypy --ignore-missing-imports . || true
      - name: Run tests
        run: pytest -q

  audit:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install pip-audit
        run: python -m pip install --upgrade pip pip-audit
      - name: Run pip-audit
        run: |
          pip-audit --progress=off

  redis-tests:
    runs-on: ubuntu-latest
    needs: test
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
    env:
      REDIS_URL: redis://redis:6379
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests against Redis-backed nonce
        env:
          REDIS_URL: redis://redis:6379
        run: pytest -q

  redis-lua-check:
    runs-on: ubuntu-latest
    needs: redis-tests
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
    env:
      REDIS_URL: redis://redis:6379
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Redis-specific Lua tests
        env:
          REDIS_URL: redis://redis:6379
        run: pytest -q tests/test_one_time_redis.py
